name = "NeoFFTV Szpital"
author = "FFTV"
version = "1.42.64-hospital.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa4d7e39209ad11ae8e5fdd2af9b999ff3fbaa19220f414e477509b0266fe8ab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
