name = "NeoFFTV Rollercoaster Tycoon Lite"
author = "FFTV"
version = "1.42.50-rc199-lite"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3a859bf00db1b90044cc098c71e8cdbf029432aaaa9b38144423dac9a582265"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
