# Iris - NeoFFTV Waterpark Tycoon Lite
# Domyslnie wylaczone: Photon v1.3b nie kompiluje sie z obecna linia Iris/Sodium.
enableShaders=false
shaderPack=photon_v1.3b.zip
maxShadowRenderDistance=32
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
